openapi: 3.1.0
info:
  title: BlindChannel REST API
  version: 0.1
paths:
  /api/registry/{alias}:
    get:
      parameters:
        - in: path
          name: alias
          required: true
          schema:
            type: string
          description: The key alias

      description: Returns a list of similar aliases, ordered by similarity
      responses:
        "500":
          description: Internal server error
        "200":
          description: List of similar aliases
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /api/search/{alias}:
    get:
      description: Returns the key associated with a given alias
      parameters:
        - in: path
          name: alias
          required: true
          schema:
            type: string
          description: The key alias

      responses:
        "500":
          description: Internal Server Error
        "404":
          description: Name not found
        "200":
          description: Key fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publicJwk'

  /api/register:
    post:
      description: Registers a name and key pair
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerRequest'
      responses:
        "201":
          description: Name and key registered successfully
        "409":
          description: Name already registered
        "500":
          description: Internal server error

  /api/publish:
    post:
      description: Publishes a message with a recipient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/publishMessage'
      responses:
        "201":
          description: Message published succesfully
        "404":
          description: Recipient name not found
        "500":
          description: Internal server error
      

  /api/messages:
    get:
      description: Returns a list of messages addressed to a given recipient
      parameters:
        - in: query
          name: recipient
          required: true
          description: The message recipient
          schema:
            type: string
        - in: query
          name: limit
          description: Limit of messages to fetch
          schema:
            type: integer
            minimum: 1

      responses:
        "500":
          description: Internal server error
        "200":
          description: Messages fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/message'


components:
  schemas:

    message:
      type: object
      properties:
        content:
          type: string
          format: byte
        sentAt:
          type: string
          format: date-time
      required:
        - content
        - sentAt

    publishMessage:
      type: object
      properties:
        content:
          type: string
          format: byte
        recipient:
          type: string
      required:
        - content
        - recipient

    registerRequest:
      type: object
      properties:
        name:
          type: string
        publicKey:
          $ref: '#/components/schemas/publicJwk'
      required:
        - name
        - publicKey

    publicJwk:
      type: object
      required:
        - e
        - n
        - alg
        - kty
      properties:
        e: 
          type: string
          enum: 
            - "AQAB"
            - "AQAB=="
        n:
          type: string
          format: byte
        alg:
          type: string
          enum:
            - RSA-OAEP-256
        kty:
          type: string
          enum:
            - RSA
        use:
          type: string
          enum:
            - enc
        
