/* tslint:disable */
/* eslint-disable */
/**
 * BlindChannel REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMessages
 */
export interface GetMessages {
    /**
     * 
     * @type {string}
     * @memberof GetMessages
     */
    recipient: string;
    /**
     * 
     * @type {number}
     * @memberof GetMessages
     */
    limit?: number;
}

/**
 * Check if a given object implements the GetMessages interface.
 */
export function instanceOfGetMessages(value: object): value is GetMessages {
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    return true;
}

export function GetMessagesFromJSON(json: any): GetMessages {
    return GetMessagesFromJSONTyped(json, false);
}

export function GetMessagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMessages {
    if (json == null) {
        return json;
    }
    return {
        
        'recipient': json['recipient'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function GetMessagesToJSON(value?: GetMessages | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'recipient': value['recipient'],
        'limit': value['limit'],
    };
}

