/* tslint:disable */
/* eslint-disable */
/**
 * BlindChannel REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NameRequest
 */
export interface NameRequest {
    /**
     * 
     * @type {string}
     * @memberof NameRequest
     */
    name: string;
}

/**
 * Check if a given object implements the NameRequest interface.
 */
export function instanceOfNameRequest(value: object): value is NameRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NameRequestFromJSON(json: any): NameRequest {
    return NameRequestFromJSONTyped(json, false);
}

export function NameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function NameRequestToJSON(value?: NameRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

